#Testing script designed to run the card deck module deck.py through its functionality to ensure all is working as designed.

import deck

TestDeck = Deck("TestDeck")
print(TestDeck.newDeck())
print(TestDeck.cardList)
print(TestDeck.shuffleDeck())
print(TestDeck.showDeck())
print(TestDeck.drawCard())
print(TestDeck.showDeck())
drawnCard = TestDeck.drawCard()
print(drawnCard)
print(TestDeck.showDeck())
print(TestDeck.returnCardTop(drawnCard))
print(TestDeck.showDeck())
drawnCard = TestDeck.drawCard()
print(drawnCard)
print(TestDeck.showDeck())
print(TestDeck.returnCardBottom(drawnCard))
print(TestDeck.showDeck())
drawnCard = TestDeck.drawCard()
print(drawnCard)
print(TestDeck.showDeck())
print(TestDeck.returnCardSpecific(drawnCard, 13))
print(TestDeck.showDeck())
drawnCard = TestDeck.drawCard()
print(drawnCard)
print(TestDeck.showDeck())
print(TestDeck.returnCardRandom(drawnCard))
print(TestDeck.showDeck())
print(TestDeck.deckDict())